nx g @trellisorg/make-buildable:migrate --projectName auth-domain --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-material --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-domain --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-ui-action-alert --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-shell --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-tile --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-button --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName administration-shell --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName auth-api --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-confirmation-dialog --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-multiple-autocomplete --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName auth-shell --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName administration-domain --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName administration-api --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-api --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName auth-forbidden --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-progress-bar --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-domain --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-aside --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-shell --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-symptom --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-data-access --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-api --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-date --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-feature-diary --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-feature-enrollment --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-feature-profile --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-feature-health-department-contact --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-feature-contact-persons --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-ui-personal-data --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-ui-contact-person-detail --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-feature-contact-cases --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-feature-index-cases --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-feature-case-detail --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName general-feature-welcome --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName general-feature-data-protection --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName general-feature-imprint --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName general-feature-terms --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName general-shell --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName administration-feature-account-detail --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName administration-feature-account-list --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-error --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName auth-feature-change-password --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName auth-feature-login --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-styles --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-forms --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-common-functions --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-snackbar --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-util-translation --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-static-pages --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-feature-export --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName client-ui-forgotten-contact-dialog --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName shared-ui-ag-grid --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName general-domain --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName general-api --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName auth-feature-reset-password --libType angular --configs production
nx g @trellisorg/make-buildable:migrate --projectName health-department-ui-export-dialog --libType angular --configs production
